"""Freebie model update

Revision ID: 185656d1de72
Revises: 06a54de47aba
Create Date: 2023-11-08 14:45:29.134340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '185656d1de72'
down_revision = '06a54de47aba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
