"""Freebie model update

Revision ID: 474dba8664eb
Revises: 185656d1de72
Create Date: 2023-11-08 14:47:38.340270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '474dba8664eb'
down_revision = '185656d1de72'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
