"""Freebie model update

Revision ID: 6574410a6f8e
Revises: a11d64f52796
Create Date: 2023-11-08 16:34:57.296093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6574410a6f8e'
down_revision = 'a11d64f52796'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
