"""Freebie model update

Revision ID: a11d64f52796
Revises: 474dba8664eb
Create Date: 2023-11-08 16:34:32.647038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a11d64f52796'
down_revision = '474dba8664eb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
