"""Models Update

Revision ID: b58f9a01c202
Revises: 6574410a6f8e
Create Date: 2023-11-09 00:36:36.277845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b58f9a01c202'
down_revision = '6574410a6f8e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
