"""Model many2many relationships update

Revision ID: b9a7820dd107
Revises: 56cf58cdaa23
Create Date: 2023-11-09 01:37:34.120917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9a7820dd107'
down_revision = '56cf58cdaa23'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
